fix(consumer): Immediatly stop polling, abort current request
bbc/sqs-consumer pull request #298
Opened 2022-02-16 12:07 UTC by yehor-manzhula

## Description
Stopping polling timeout and current polling request.

## Motivation and Context
Stop method doesn't gracefully terminate polling:
1. Stop method doesn't abort current polling request
2. "Stopped" event emitted after polling timeout execution, that doesn't make any sense.

Actuall polling stop depends on: 
 waitTimeSeconds + Messages processing time + pollingWaitTimeMs 
[Multiple polls invoked](https://github.com/bbc/sqs-consumer/issues/234)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-08-31 05:25 UTC, ankitgehlot123 approved these changes

2022-12-16 23:26 UTC, nicholasgriffintn requested changes

2022-12-16 23:26 UTC, nicholasgriffintn commented on src/consumer.ts
> +    return err.statusCode === 200 || err.code === 'RequestAbortedError';
Not sure we want to consider everything with a status code 200 as an abort error...

2022-12-16 23:26 UTC, nicholasgriffintn commented on src/consumer.ts
> +import { AWSError, SQS, Request as AWSRequest } from 'aws-sdk';
This will all need to be updated to AWS SDK V3

2022-12-16 23:26 UTC, nicholasgriffintn commented on src/consumer.ts
> +        throw sqsError;
Do we not want to throw this error still? I think we probably do...

2022-12-16 23:26 UTC, nicholasgriffintn commented on src/consumer.ts
> -      this.emit('stopped');
I'm unsure why this has been removed.

2022-12-16 23:26 UTC, nicholasgriffintn commented on src/consumer.ts
> +  private currentPollingRequest: AWSRequest<
Not to sure about this overall implementation.

2022-12-18 03:35 UTC, nicholasgriffintn commented
Closing this PR given the age and changes requested above, if you would still like to contribute please open a new PR, we may look into this separately as well.

2022-12-18 03:35 UTC, closed without merging